### ISSUE TITLE
Error during job creation

### ISSUE THREAD

**Issue by ericdatakelly** [nebari-dev/argo-workflows-executor#11]
### Context

After choosing options for a job, I click `Create` and get "Unexpected error occurred during creation of job." I've tried with a couple of different notebooks, including a very simple one.  I added papermill to the conda environment, then tried adding juptyer as well.  Neither of these had a perceivable effect.  I also put the notebook in a shared folder in case it's a permission issue.

![argo-jupyter](https://github.com/nebari-dev/argo-jupyter-scheduler/assets/24855669/81855730-8f7b-4343-8096-70a76cf5a1c9)

### Value and/or benefit

There's a bug or something else preventing the scheduler from running.

**Comment by krassowski** [comment]
This is likely the same as https://github.com/jupyter-server/jupyter-scheduler/issues/519. We pinned jupyter-scheduler version in https://github.com/nebari-dev/nebari-docker-images/pull/148 but that was not released yet.

**Comment by andrii-i** [comment]
Hi everyone. I've seen this issue linked in https://github.com/jupyter-server/jupyter-scheduler/issues/519 and wanted to let you know that I just released Jupyter Scheduler [v2.7.0](https://github.com/jupyter-server/jupyter-scheduler/releases/tag/v2.7.0) that among other things adds a database migration / table extension logic ([#520](https://github.com/jupyter-server/jupyter-scheduler/pull/520)). Thank you @krassowski for creating the issue https://github.com/jupyter-server/jupyter-scheduler/issues/519.

**Comment by kcpevey** [comment]
This will be included in the 2024.6.1 release.

**Comment by Adam-D-Lewis** [comment]
Fixed in 2024.6.1, closing.
