### ISSUE TITLE
[ENH] - Update for Jupyterlab 4 compatibility

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/argo-workflows-executor#4]
### Feature description

Now that Jupyterlab 4 is available and projects are moving onto it, we need to test this package and see what needs to be done to update it for compatibility. 

### Value and/or benefit

JLab 4 compatibility

**Comment by kcpevey** [comment]
jupyter-scheduler introduced breaking changes when [they upgraded to JLab 4](https://github.com/jupyter-server/jupyter-scheduler/pull/402). This probably means that this package will require some changes as well.

**Comment by nkaretnikov** [comment]
No changes needed. Replied in https://github.com/nebari-dev/nebari/issues/2195#issuecomment-1886155081.

Suggested to merge https://github.com/nebari-dev/argo-jupyter-scheduler/pull/3 as part of this Nebari release. ~~Waiting for Dharhas to respond on the linked issue.~~

UPD: Dharhas approved my idea to merge the PR, so I did. I'll re-test and update the issue.

UPD2: Submitted a PR with a new release here https://github.com/nebari-dev/nebari-docker-images/pull/108
