### ISSUE TITLE
Can we raise a more informative error when `papermill` is not installed?

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/argo-workflows-executor#8]
### Context

When papermill is not in environment the job fails without any sensible description. There are some ideas to solve it with LBYL (https://github.com/nebari-dev/nebari/issues/1838):

https://github.com/nebari-dev/argo-jupyter-scheduler/blob/1d9f1d175dd40a2dfc25497f215f60e4fec24e56/argo_jupyter_scheduler/utils.py#L135-L137

but I think what would be neat is if we could return an informative error from the container itself:

currently it just shows "Workflow failed"

![image](https://github.com/nebari-dev/argo-jupyter-scheduler/assets/5832902/fbbab12c-2a0e-476b-bb0c-67046dd205ef)

Maybe it is as simple as adjusting these lines:

https://github.com/nebari-dev/argo-jupyter-scheduler/blob/1d9f1d175dd40a2dfc25497f215f60e4fec24e56/argo_jupyter_scheduler/utils.py#L207-L210

?

### Value and/or benefit

Less user confusion. Users using the scheduler function rather than giving up after first attempt because it is not working.

**Comment by Adam-D-Lewis** [comment]
Definitely agree with this :+1:

**Comment by nkaretnikov** [comment]
I've implemented this in #10.
