### ISSUE TITLE
Raise more informative error message when user doesn't have adequate permissions

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/argo-workflows-executor#9]
### Context

See https://github.com/nebari-dev/nebari/issues/2444
A more informative error message would really help with debugging

### Value and/or benefit

Better User experience, less frustration, wasted time

**Comment by nkaretnikov** [comment]
An error message is already raised when there are permission issues. I also added a PR to Nebari docs to clarify how to configure groups and troubleshoot permission issues, see my comment here: https://github.com/nebari-dev/nebari/issues/2444#issuecomment-2132711794
